name: Android Gradle Build on push

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ develop ]

jobs:
  Gradle_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Gradle build
        run: ./gradlew build