name: Create signed Release artifacts on tag

on:
  push:
    tags:
      - '*'

jobs:
  Build_release_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Java17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Write run number to properties
        run: echo ciBuildNumber=${{ github.run_number }} > ./local.properties

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: .github/workflows/parameters
          mode: normalParameters

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/${{ env.KEYSTORE_FILE_NAME }}
          echo "${TMP_KEYSTORE_FILE_PATH}"/${{ env.KEYSTORE_FILE_NAME }}

      - name: Build Release signed apk
        run: ./gradlew assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Rename built Flavor1 apk artifact
        run: mv ${{ env.FLAVOR1_BUILT_APK_DIR }}${{ env.FLAVOR1_BUILT_APK_NAME }} ${{ env.FLAVOR1_BUILT_APK_DIR }}${{ env.FLAVOR1_RENAMED_APK_NAME }}_${{ github.run_number }}.apk

      - name: Rename built Flavor2 apk artifact
        run: mv ${{ env.FLAVOR2_BUILT_APK_DIR }}${{ env.FLAVOR2_BUILT_APK_NAME }} ${{ env.FLAVOR2_BUILT_APK_DIR }}${{ env.FLAVOR2_RENAMED_APK_NAME }}_${{ github.run_number }}.apk

      - name: Export Flavor1 release apk
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.FLAVOR1_BUILT_APK_DIR }}${{ env.FLAVOR1_RENAMED_APK_NAME }}_${{ github.run_number }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Export Flavor2 release apk
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.FLAVOR2_BUILT_APK_DIR }}${{ env.FLAVOR2_RENAMED_APK_NAME }}_${{ github.run_number }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Release signed aab
        run: ./gradlew bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Rename built Flavor1 aab artifact
        run: mv ${{ env.FLAVOR1_BUILT_AAB_DIR }}${{ env.FLAVOR1_BUILT_AAB_NAME }} ${{ env.FLAVOR1_BUILT_AAB_DIR }}${{ env.FLAVOR1_RENAMED_AAB_NAME }}_${{ github.run_number }}.aab

      - name: Rename built Flavor2 aab artifact
        run: mv ${{ env.FLAVOR2_BUILT_AAB_DIR }}${{ env.FLAVOR2_BUILT_AAB_NAME }} ${{ env.FLAVOR2_BUILT_AAB_DIR }}${{ env.FLAVOR2_RENAMED_AAB_NAME }}_${{ github.run_number }}.aab

      - name: Export Flavor1 release aab
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.FLAVOR1_BUILT_AAB_DIR }}${{ env.FLAVOR1_RENAMED_AAB_NAME }}_${{ github.run_number }}.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Export Flavor2 release aab
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.FLAVOR2_BUILT_AAB_DIR }}${{ env.FLAVOR2_RENAMED_AAB_NAME }}_${{ github.run_number }}.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move artifacts to proper dir
        run: |
          mkdir app/build/output_${{ github.run_number }}
          mv app/build/outputs/* app/build/output_${{ github.run_number }}
          mv app/build/generated/source/* app/build/output_${{ github.run_number }}
          mv app/build/intermediates/merged_manifests/* app/build/output_${{ github.run_number }}

      - name: Create archive
        run: tar -czvf app/build/output_${{ github.run_number }}.tar.gz app/build/output_${{ github.run_number }}

      - name: Export release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/output_${{ github.run_number }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}