name: Android Gradle Build on push and PR

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ master, develop ]

jobs:
  Gradle_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: .github/workflows/parameters
          mode: normalParameters

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/${{ env.KEYSTORE_FILE_NAME }}
          echo "${TMP_KEYSTORE_FILE_PATH}"/${{ env.KEYSTORE_FILE_NAME }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Lint
        run: ./gradlew lint -x :play-licensing:lintDebug

      - name: Gradle build
        run: ./gradlew build -x :play-licensing:lintDebug
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

  Sonar_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: .github/workflows/parameters
          mode: normalParameters

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/${{ env.KEYSTORE_FILE_NAME }}
          echo "${TMP_KEYSTORE_FILE_PATH}"/${{ env.KEYSTORE_FILE_NAME }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Sonar analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew buildFlavor1Debug sonar --info -x :play-licensing:lintDebug

  Unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Unit tests
        run: ./gradlew test